### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by hadrienl** [zewa666/angular_es6#2]
Hi,

I love your project skeleton and I'm working on making it the foundation of my new project. All is working fine but there is no building process for the production. Could you help me to write a 'bundle' task which will bundle the scripts and make loading the app with the minimal amount of files?

Thank you for your work.

**Comment by hadrienl** [comment]
Ok, I've found the doc of jspm bundle. But the build fail because of `@register` decorator which use `System.import` which is forbidden in bundled mode… Do you know another way to register modules without using `System.import`?

**Comment by zewa666** [comment]
Hi @hadrienl, good idea. I just need the repo as it is for my conference talk on Monday, as I don't want to introduce any untested errors :)

As soon as I'm back next week I'll work that one out. System.import was so far needed as a timing helper for getting the angular.module setup properly, since the decorator actually gets called before the angular.module is created.
But with a bit fiddling we should get that to work with a simple

```
import angular from 'angular';
```

**Comment by hadrienl** [comment]
I've tried this :

```
export function register (opts) {
  return function decorate(target) {
    function _decorate (target, opts) {
      if(opts.inject) {
        target.$inject = opts.inject;
      }

      var app = angular.module('app');
      let name = opts.name || target.name;
      app[opts.type](name, target);
    }
    try {
      _decorate(target, opts);
    } catch (err) {
      setTimeout(() => _decorate(target, opts));
    }
  };
}
```

It worked in dev mode, but not in bundled mode neither :(

**Comment by zewa666** [comment]
yep, will get to that, maybe in the meantime you could contribute a gulp task for the production build? That would be a big help. You can try out the example without using the decorator

**Comment by hadrienl** [comment]
Oh ! It seems to work by delaying app bootstrap :

```
angular.element(document).ready(function() {
  setTimeout(() => angular.bootstrap(document, ['sleek']), 10);
});
```

I'll make a PR tomorrow :)

**Comment by zewa666** [comment]
Ok great, as said take your time, I will be only able to merge this by mid next week

**Comment by hadrienl** [comment]
:( I have the same problem with karma… but I don't know where to delay the tests's start…
